services:
  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: qkd_db
      POSTGRES_USER: qkd_user
      POSTGRES_PASSWORD: qkd_password
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: qkd_db
      MYSQL_USER: qkd_user
      MYSQL_PASSWORD: qkd_password
      MYSQL_ROOT_PASSWORD: root_password
  mariadb:
    image: mariadb:latest
    ports:
      - "3307:3306"
    environment:
      MARIADB_DATABASE: qkd_db
      MARIADB_USER: qkd_user
      MARIADB_PASSWORD: qkd_password
      MARIADB_ROOT_PASSWORD: root_password
